[package]
name = "librawssg"
version = "0.4.0"
edition = "2024"
description = "Engine-agnostic, safety-first kernel for building static site generators in Rust"
license = "MIT"
repository = "https://github.com/mroczect/librawssg"
homepage = "https://github.com/mroczect/librawssg"
documentation = "https://docs.rs/librawssg"
readme = "README.md"
keywords = ["static-site-generator", "ssg", "libary", "kernel", "rawssg"]
categories = ["web-programming", "template-engine", "development-tools"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2"
miette = { version = "7", features = ["fancy"] }
tracing = "0.1"
walkdir = "2"
chrono = { version = "0.4", features = ["serde"] }
glob = "0.3"

tera = { version = "2", optional = true }
pulldown-cmark = { version = "0.13", optional = true }

# Serve feature
tiny_http = { version = "0.12", optional = true }
notify = { version = "8", optional = true }

[features]
default = []
tera = ["dep:tera"]
pulldown = ["dep:pulldown-cmark"]
serve = ["dep:tiny_http", "dep:notify"]

[dev-dependencies]
pulldown-cmark = "0.13"
tempfile = "3.27.0"
tera = "2"